add_test( [==[Scenario: Evaluate Code for Task 1]==] /workspaces/lab01-danielteberian/tests [==[Scenario: Evaluate Code for Task 1]==]  )
set_tests_properties( [==[Scenario: Evaluate Code for Task 1]==] PROPERTIES WORKING_DIRECTORY /workspaces/lab01-danielteberian)
add_test( [==[Scenario: Evaluate Code for Task 2]==] /workspaces/lab01-danielteberian/tests [==[Scenario: Evaluate Code for Task 2]==]  )
set_tests_properties( [==[Scenario: Evaluate Code for Task 2]==] PROPERTIES WORKING_DIRECTORY /workspaces/lab01-danielteberian)
add_test( [==[Scenario: Evaluate Code for Task 3]==] /workspaces/lab01-danielteberian/tests [==[Scenario: Evaluate Code for Task 3]==]  )
set_tests_properties( [==[Scenario: Evaluate Code for Task 3]==] PROPERTIES WORKING_DIRECTORY /workspaces/lab01-danielteberian)
set( tests_TESTS [==[Scenario: Evaluate Code for Task 1]==] [==[Scenario: Evaluate Code for Task 2]==] [==[Scenario: Evaluate Code for Task 3]==])
